export const ui = {
  search: {
    placeholder: 'Введіть назву напою або бренду',
    button: 'Знайти',
    noResults: 'Нічого не знайдено',
    popularQueries: ['Martini', 'Jack Daniel\'s', 'Prosecco', 'Moët', 'Absolut'],
  },
  nav: {
    myList: 'Мій список',
  },
  hero: {
    title: 'Знайди улюблений напій',
    subtitle: 'за найкращою ціною поруч',
    valueProposition: 'Додайте напої до списку покупок та порівняйте ціни у найближчих магазинах',
    stats: 'Понад 100 000 товарів у 100+ магазинах України',
  },
  catalog: {
    filters: 'Фільтри',
    sortBy: 'Сортувати',
    popular: 'Популярні',
    priceAsc: 'Ціна ↑',
    priceDesc: 'Ціна ↓',
    inStores: (n: number) => `у ${n} магазинах`,
    fromPrice: (p: string) => `від ${p}`,
    toList: 'До списку',
    inList: '✓ У списку',
    whereToBuy: 'Де купити',
    topProducts: 'Популярні товари',
    recommendations: 'Часто шукають',
    allCategories: 'Усі категорії',
    viewAll: 'Переглянути всі',
  },
  categories: {
    heading: 'Каталог напоїв',
    subtitle: 'Оберіть категорію та додайте товари до списку покупок',
    viewAll: 'Усі категорії →',
  },
  howItWorks: {
    heading: 'Як це працює',
    subtitle: 'Знайдіть де купити весь список за найкращою ціною поруч з вами',
    step1Title: 'Додайте напої до списку',
    step1Desc: 'Вино, пиво, віскі — будь-що. Створіть свій список покупок за кілька кліків.',
    step2Title: 'Ми знайдемо ціни поруч',
    step2Desc: 'Порівнюємо ціни у найближчих магазинах і показуємо де купити дешевше.',
    step3Title: 'Оберіть найкращий магазин',
    step3Desc: 'Обирайте за ціною, відстанню або покриттям списку — і економте на кожній покупці.',
    cta: 'Почати формувати список →',
  },
  listPreview: {
    heading: 'Ваш список покупок',
    empty: 'Список порожній — додайте товари з каталогу',
    itemsCount: (n: number) => `${n} ${n === 1 ? 'товар' : n < 5 ? 'товари' : 'товарів'} додано`,
    findStores: 'Знайти де купити →',
    goToList: 'Перейти до списку',
    addMore: 'Додати ще товарів',
    hint: 'Далі: знайти магазини і порівняти ціни',
  },
  trust: {
    heading: 'Чому Alcoplace',
    items: [
      { value: '100 000+', label: 'товарів у каталозі', icon: '📦' },
      { value: '100+', label: 'магазинів по Україні', icon: '🏪' },
      { value: '30', label: 'міст з покриттям', icon: '🗺️' },
      { value: '< 5 сек', label: 'найкраща ціна за кілька секунд', icon: '⚡' },
    ],
  },
  filters: {
    category: 'Категорія',
    price: 'Ціна',
    country: 'Країна',
    alcohol: 'Міцність',
    brand: 'Бренд',
    color: 'Колір',
    sweetness: 'Солодкість',
    colors: {
      red: 'Червоне',
      white: 'Біле',
      rose: 'Рожеве',
    },
    sweetnesses: {
      dry: 'Сухе',
      semiDry: 'Напівсухе',
      semiSweet: 'Напівсолодке',
      sweet: 'Солодке',
    },
  },
  product: {
    addToList: 'Додати до списку',
    reviews: (n: number) => `${n} відгуків`,
    availableIn: (n: number) => `Доступно у ${n} магазинах`,
    whereToBuy: 'Де купити поруч',
    similar: 'Схожі товари',
    store: 'Магазин',
    price: 'Ціна',
    availability: 'Наявність',
    inStock: 'В наявності',
    lowStock: 'Закінчується',
    outOfStock: 'Немає',
  },
  list: {
    title: 'Мій список',
    empty: 'Список порожній',
    emptyHint: 'Додайте товари з каталогу, щоб знайти найкращі ціни поруч',
    goToCatalog: 'Перейти до каталогу',
    findStores: 'Знайти магазини',
    byCoverage: 'За покриттям',
    byDistance: 'За відстанню',
    itemsOf: (found: number, total: number) => `${found} з ${total} товарів`,
    total: 'разом',
    map: 'Карта',
    listView: 'Список',
  },
  ageGate: {
    question: 'Вам є 18 років?',
    yes: 'Так, мені є 18',
    no: 'Ні',
  },
  footer: {
    tagline: 'Порівнюй ціни. Знаходь поруч.',
    catalog: 'Каталог',
    about: 'Про нас',
    contacts: 'Контакти',
    bottomCta: 'Знайди найкращу ціну поруч з тобою',
  },
} as const
